### ISSUE TITLE
GRAInitialAuthCode Denial

### ISSUE THREAD

**Issue by AgentofLucian** [MCLD/greatreadingadventure#728] opened 2021-03-05 20:30 UTC
Description of issue
In initial setup, GRAInitialAuthCode is declared as "<secretpassword">, when set and ran through localhost/join/authorizationcode, the password entered is continuously denied.
## Steps to reproduce
1. Set GRAInitialAuthCode in appsettings.json to desired password
2. Navigate to localhost/Join/AuthorizationCode
3. Enter password
## Expected behavior
1. Admittance into admin settings
## Actual behavior
1. Password continuously rejected

**Comment by k7hpn** [comment] 2021-03-05 23:33
This may be due to special characters in the password, we've had issues with passwords that contain `!` and `%`. I will take a look.

**Comment by k7hpn** [comment] 2021-03-09 18:03
It'd be good to know the format of what you put in the config file, even if you can mask it out (e.g. if your password was `hunter2` you could just say you used `xxxxxx0`.

The line in your `appsettings.json` file would look like:

```json
  "GraInitialAuthCode": "xxxxxx0",
```

The change that allows special characters should be ready to go in soon so at least that aspect will be fixed.

**Comment by AgentofLucian** [comment] 2021-03-09 19:07
Absolutely no problem! the exact syntax and password is: 
{
"ConnectionStrings": {
"SqlServer": "Server=XXX.XXX.XXX.XXX;
Database=GenericName;
user id=generic_user;
password=SwordBronze187Hunter;
MultipleActiveResultSets=true"
                                   }, 
"GraInitialAuthCode": "CopperHammer112Heavy"
}
These are just fillers, but the syntax and layout of the sensitive info is the same. 
Let me know if there is anything else I can do, thank you again!

**Comment by k7hpn** [comment] 2021-03-09 19:52
Hmm, do you know if the issue was with the connection to the SQL Server database or the initial auth code? I've never seen a SQL Server connection string with line breaks in it before but I don't know if there's an issue with that or not. Is there anything in the logs indicating what the issue is (the logs should be in `shared/logs/`).

I was able to use that exact code in my configuration, so I can't reproduce this locally at the moment, grr.

Sorry you're having this issue!

**Comment by AgentofLucian** [comment] 2021-03-09 21:51
I am absolutely no expert, but I believe that the issue is with the initial auth code, if I change anything from the server name to the password, the whole application breaks and doesn't load. I can definitely check the logs again tomorrow morning, but as it is a work issue, I got kicked out of the office at closing time.

And no worries, i'm honestly grateful that you're even willing to help! I've reached out for help a few times now on different platforms and you are by-far the best, and nicest.

**Comment by AgentofLucian** [comment] 2021-03-10 14:49
Hi so, after checking the logs I noticed that it was failing to log in with the db-user, so I went ahead and fixed that. However, no change on the authorization issue.

**Comment by k7hpn** [comment] 2021-03-10 17:24
Well this sure is weird.

My thought at this point is that maybe the database didn't get the initial records inserted (specifically the initial auth code). In your situation I'd probably recreate the database but I realize that might not be super-easy for you to do. If you can get to a SQL prompt (e.g. using SQL Server Management Studio) you could check if there are any authorization codes in the table:

```sql
SELECT * FROM [AuthorizationCodes]
```

You can also manually insert an additional code with a SQL statement like:

```sql
INSERT INTO [AuthorizationCodes]
  ([Code], [CreatedAt], [CreatedBy], [Description], [IsSingleUse], [RoleId], [SiteId], [Uses])
  VALUES
  ('CopperHammer112Heavy', GETDATE(), 1, 'Test code inserted manually', 0, 1, 1, 0)
```

**Comment by AgentofLucian** [comment] 2021-03-10 17:41
So it did populate an auth code, I can't necessarily cut and paste what it says but essentially its:
ID:1, Code:<authorizationcode>, CreatedAt:2021-03-05, CreatedBy:1, Description:Initial code to grant system administrator status., IsSingleUse:0, RoleId:1, SiteId:1, Uses:0

Seeing that, i went ahead and tried <authorizationcode> as the password, but that was unsuccessful.  I'll go ahead and try the second part of your comment now.

**Comment by AgentofLucian** [comment] 2021-03-10 17:45
The second command worked! So is it that for some reason it never populated the correct authorization code?

**Comment by k7hpn** [comment] 2021-03-10 20:12
I'm glad it's working! Please don't hesitate to contact us on here (or me directly) if you have any more comments/questions about the GRA and how it works!!

I've created a PR with a little more logging during initial setup: Add logging on initial site and authorization code insert #736 

At least for our next release there will be a little more logging surrounding the initial configuration process.

I'm going to close this issue out, feel free to open additional issues or start discussions if necessary!

**Closed by k7hpn** 2021-03-10 20:12 UTC
Labels: bug
